### PR TITLE
Add mesh surface picking, drag & drop info labels

### PR DESCRIPTION
**Pull request by gaudecker**
Ping @SaracenOne

- Adds surface picking for meshes to material drag and drop when holding <kbd>ctrl</kbd>
- Show info label when dragging

Screenshot from 2022-04-06 09-14-03

### CODE REVIEW

**Comment by SaracenOne** [comment]
Thanks! Going to test it now

**Comment by gaudecker** [comment]
Hmm. If you're dragging a texture, try re-importing it. It should work 🤔

**Comment by SaracenOne** [comment]
It's not working at the moment for dragging either textures or materials. It gives me the prompt when I'm dragging into the viewport, but I can't drop it on anything

**Comment by SaracenOne** [comment]
@gaudecker Okay, after poking around at this for a while, I think I found out what was going wrong. Why it's going wrong is another question, but the ray picker in the 3D editor was indeed broken on my local build. The cause? Using a release_debug build rather than a pure debug build. I've tested it with debug though and it seems these changes are good though

**Pull request merged**
